image:
  file: .gitpod.Dockerfile

tasks:
  - name: Hello World
    init: |
      export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
      export AWS_SECRET_ACCESS_KEY="$AWS_SECRETS_ACCESS_KEY"
      export AWS_DEFAULT_REGION="us-east-1"
    command: echo "Hello World"