image:
  file: .gitpod.Dockerfile

tasks:
  - name: Your Command Line!
    init: >
      export AWS_DEFAULT_REGION=us-east-1 &&
      gp env AWS_VAULT_FILE_PASSPHRASE=password &&
      aws-vault add default --backend=file --env
    command: ./setup.sh